### ISSUE TITLE
The display of updated packages does not work correctly.

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/update-buddy#3] opened 2023-06-01 11:20 UTC
update-buddy does not search independently for which packages need to be updated and the output screen displays the packages that are hidden for update. Is it possible to display information correctly in the program window?  (if appropriate, as Bullseye has a built-in)

RaspiOS 32bit Debian10

![Безымянный](https://github.com/Botspot/update-buddy/assets/88277343/ccd4087f-e060-47a6-8c47-42990842b062)

**Comment by Botspot** [comment] 2023-06-01 12:52
You can see line 34 of `onstartup.sh` to see exactly how it generates the list to display to you.
Try running that in a terminal.
```
apt list --upgradable 2>/dev/null | cut -d/ -f 1 | tail -n +2 | grep -vx "$(dpkg --get-selections | grep "\<hold$" | tr -d ' \t' | sed 's/hold//g' | sed -z 's/\n/\\|/g' | sed -z 's/\\|$/\n/g')"
```
If it only says `linux-libc-dev`, then either something needs to be tweaked, or all of your other upgradable packages are marked as "held".
However, if it lists all upgradable packages correctly, then my guess is that Update Buddy did not successfully complete its `sudo apt update` when you first booted up, and `linux-libc-dev` was previously the only upgradable package as of the last time an `apt update` successfully completed. In this case there is not much I can do to fix it, as it would depend on how your apt system is configured.

**Comment by Rak1ta** [comment] 2023-06-07 07:30
@Botspot In my case, update-buddy does not independently offer new updates. And the linux-libc-dev package is hidden (hold) for me.
![Безымянный](https://github.com/Botspot/update-buddy/assets/88277343/6e5d4c33-2a4b-4f36-9d98-10eb7fac4610)

**Comment by Botspot** [comment] 2023-06-07 20:41
It does appear that some packages are missing from the output of the command I asked to to run. I need your help to see what is going on.

Please paste the full output of `apt list --upgradable` here on github.
Please also run this and paste the output into github: `dpkg --get-selections | grep "\<hold$" | tr -d ' \t' | sed 's/hold//g' | sed -z 's/\n/\\|/g' | sed -z 's/\\|$/\n/g'`

**Comment by Rak1ta** [comment] 2023-06-07 21:08
@Botspot As I understand it, the script does not make an apt update and displays what is already known. I cannot show anything new now, since I only have packages that I have forbidden to update.
![image](https://github.com/Botspot/update-buddy/assets/88277343/9032535d-f615-4899-9c59-e569cce973c6)

**Comment by Botspot** [comment] 2023-06-07 21:58
No, it runs `sudo apt update`.
Try this:
```
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
sudo apt update
```
I want to see if it outputs in english or in your chosen language. Update buddy tries to make it output in english in order to check for the phrase "can be upgraded".

**Comment by Rak1ta** [comment] 2023-06-08 04:30
> Try this

Output in the terminal is in English

**Comment by Botspot** [comment] 2023-06-08 06:21
I am not sure what to check at this point. Obviously, some packages in the `apt list --upgradable` are going missing in the technique Update Buddy uses to get them. But I have never noticed this issue on my system, which means I can't think of a way to test it myself. I know what command is going wrong on your system, but more investigation is needed. I just need you to run portions of that long command step by step to see what happened.

@Rak1ta, Since you have already upgraded your packages, we cannot investigate now. Please reply back when you encounter this issue again when more packages can again be upgraded. (And then please don't upgrade them until we get it sorted out)

**Comment by Rak1ta** [comment] 2023-06-08 06:29
@Botspot I can invite you to AnyDesk when the updates appear

**Comment by Rak1ta** [comment] 2023-06-28 07:50
@Botspot Can you tell me which commands I have to execute? I forgot that pi-apps does "sudo apt update" and again I will not be able to reproduce the error. 

> I know what command is going wrong on your system

I want to test it myself, but I don't know the command for the console.

**Comment by Botspot** [comment] 2023-06-28 13:19
Well based on what you have told me, it seems like update buddy is successfully running `apt update`, but it fails to retrieve the full list of upgradable packages.
The line of code to construct that list is:
```
apt list --upgradable 2>/dev/null | cut -d/ -f 1 | tail -n +2 | grep -vx "$(dpkg --get-selections | grep "\<hold$" | tr -d ' \t' | sed 's/hold//g' | sed -z 's/\n/\\|/g' | sed -z 's/\\|$/\n/g')"
```
Once you find a situation where you know more packages are upgradable than Update Buddy is showing you, then I would ask you to first run that command, then take off one part of the bash pipe at a time to pinpoint which step is incorrectly deleting some packages from the list.
Like this:
```
apt list --upgradable 2>/dev/null | cut -d/ -f 1 | tail -n +2 | grep -vx "$(dpkg --get-selections | grep "\<hold$" | tr -d ' \t' | sed 's/hold//g' | sed -z 's/\n/\\|/g' | sed -z 's/\\|$/\n/g')"
apt list --upgradable 2>/dev/null | cut -d/ -f 1 | tail -n +2
apt list --upgradable 2>/dev/null | cut -d/ -f 1
apt list --upgradable 2>/dev/null
```

**Comment by Rak1ta** [comment] 2023-07-12 18:58
@Botspot 
![Безымянный](https://github.com/Botspot/update-buddy/assets/88277343/f7907bc9-6711-4586-ba98-6a34043660a9)

```
pi@raspberrypi:~ $ sudo apt-mark showhold
box86
libraspberrypi-bin
libraspberrypi-dev
libraspberrypi-doc
libraspberrypi0
libsdl1.2-dev
libsdl2-dev
linux-libc-dev                        <<<
raspberrypi-bootloader
raspberrypi-kernel
raspberrypi-kernel-headers
scratch2
```

```
pi@raspberrypi:~ $ apt list --upgradable 2>/dev/null
Вывод списка… Готово
adoptium-ca-certificates/buster 1.0.2-1 all [может быть обновлён с: 1.0.1-1]
avahi-daemon/oldstable 0.7-4+deb10u3 armhf [может быть обновлён с: 0.7-4+deb10u1]
box86/неизвестно 0.3.1+20230625.b7283b8-1 armhf [может быть обновлён с: 0.2.9+20230305.5bb4731-1]
cawbird/неизвестно 1.5-1+6.23 armhf [может быть обновлён с: 1.5-1+6.22]
firefox/bionic 115.0+build1-0ubuntu0.18.04.1~mt1 armhf [может быть обновлён с: 114.0.1+build1-0ubuntu0.18.04.1~mt1]
libavahi-client3/oldstable 0.7-4+deb10u3 armhf [может быть обновлён с: 0.7-4+deb10u1]
libavahi-common-data/oldstable 0.7-4+deb10u3 armhf [может быть обновлён с: 0.7-4+deb10u1]
libavahi-common3/oldstable 0.7-4+deb10u3 armhf [может быть обновлён с: 0.7-4+deb10u1]
libavahi-core7/oldstable 0.7-4+deb10u3 armhf [может быть обновлён с: 0.7-4+deb10u1]
libavahi-glib1/oldstable 0.7-4+deb10u3 armhf [может быть обновлён с: 0.7-4+deb10u1]
libfastjson4/oldstable 0.99.8-2+deb10u1 armhf [может быть обновлён с: 0.99.8-2]
libhsqldb1.8.0-java/oldstable 1.8.0.10+dfsg-10+deb10u1 all [может быть обновлён с: 1.8.0.10+dfsg-10]
libraspberrypi-bin/oldstable 1:1.20230509~buster-1 armhf [может быть обновлён с: 1:1.20220308~buster-1]
libraspberrypi-dev/oldstable 1:1.20230509~buster-1 armhf [может быть обновлён с: 1:1.20220308~buster-1]
libraspberrypi-doc/oldstable 1:1.20230509~buster-1 armhf [может быть обновлён с: 1:1.20220308~buster-1]
libraspberrypi0/oldstable 1:1.20230509~buster-1 armhf [может быть обновлён с: 1:1.20220308~buster-1]
libxpm-dev/oldstable 1:3.5.12-1+deb10u1 armhf [может быть обновлён с: 1:3.5.12-1]
libxpm4/oldstable 1:3.5.12-1+deb10u1 armhf [может быть обновлён с: 1:3.5.12-1]
linux-libc-dev/oldstable 1:1.20230509~buster-1 armhf [может быть обновлён с: 1:1.20220308~buster-1]
palemoon/неизвестно 32.2.1-1.gtk2 armhf [может быть обновлён с: 32.2.0-2.gtk2]
python-mechanize/oldstable 1:0.2.5-3+deb10u1 all [может быть обновлён с: 1:0.2.5-3]
python-requests/oldstable 2.21.0-1+deb10u1 all [может быть обновлён с: 2.21.0-1]
python3-requests/oldstable 2.21.0-1+deb10u1 all [может быть обновлён с: 2.21.0-1]
raspberrypi-bootloader/oldstable 1:1.20230509~buster-1 armhf [может быть обновлён с: 1:1.20220308~buster-1]
raspberrypi-kernel-headers/oldstable 1:1.20230509~buster-1 armhf [может быть обновлён с: 1:1.20220308~buster-1]
raspberrypi-kernel/oldstable 1:1.20230509~buster-1 armhf [может быть обновлён с: 1:1.20220308~buster-1]
scratch2/oldstable 0.26 armhf [может быть обновлён с: 0.25]
vivaldi-stable/stable 6.1.3035.111-1 armhf [может быть обновлён с: 6.1.3035.84-1]
```

If I check for updates myself: (227 packages)
[apt update.txt](https://github.com/Botspot/update-buddy/files/12031302/apt.update.txt)

**Comment by Botspot** [comment] 2023-07-13 02:30
Thank you. I will try to review this tomorrow. If possible, please try not to upgrade your system, so that if I need additional commands to be run that we don't have to wait another month. Or if it is easier, you could copy this current state of your SD card to another one so that you can 'freeze' this state of your OS to return to, for testing.

**Comment by Botspot** [comment] 2023-07-13 04:57
@Rak1ta, based on your command output, either the 2>/dev/null is somehow removing some of the packages in the list, or more packages became updatable after you ran an apt update manually.
Please run this:
```
apt list --upgradable 2>/dev/null
apt list --upgradable
```
Please let me know if the list of packages is the same for both commands, or if some are missing from the command with `2>/dev/null`.

**Comment by Rak1ta** [comment] 2023-07-13 06:29
@Botspot I have a question, does this work in your script? 
  `output="$(sudo apt update 2>&1)" `

**Comment by Rak1ta** [comment] 2023-08-17 09:46
@Botspot Is this updatable query waiting for the "sudo apt update" command to finish? I can only assume that your script shows the last successful search for updates. Since if you manually search for updates, then update-buddy.
Is there an opportunity in the console to see how the script works?
https://github.com/Botspot/update-buddy/blob/f42ef7d34de9e7cbbbca36040061eab54a9ea8e6/onstartup.sh#L27

**Comment by Botspot** [comment] 2023-08-17 20:11
@Rak1ta, this modified version of onstartup.sh includes some logging. My current guess about your situation is that the apt update is sometimes failing on startup for some reason. When it happens again, the logfile should help show exactly what happened.
```bash
#!/bin/bash

DIRECTORY="$(readlink -f "$(dirname "$0")")"

echo "$(date) update buddy started." >> ~/update-buddy.log

#From pi-apps add_englich function
if [ "$(cat /usr/share/i18n/SUPPORTED | grep -o 'en_US.UTF-8' )" == "en_US.UTF-8" ]; then
  locale=$(locale -a | grep -oF 'en_US.utf8')
  if [ "$locale" != 'en_US.utf8' ]; then
    status "Adding en_US locale for better logging... "
    sudo sed -i '/en_US.UTF-8/s/^#[ ]//g' /etc/locale.gen
    sudo locale-gen
  fi
else
    warning "en_US locale is not available on your system. This may cause bad logging experience."
fi
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

while true;do
  update=1
  
  output="$(sudo apt update 2>&1)"
  exitcode=$?
  
  #inform user packages are upgradeable
  if [ -z "$(echo "$output" | grep 'can be upgraded' )" ];then
    echo "$(date) apt update output did not include 'can be updated'." >> ~/update-buddy.log
    update=0
  elif [ $exitcode != 0 ];then
    echo "$(date) apt update failed." >> ~/update-buddy.log
    update=0
  fi
  echo "APT output was: $output" >> ~/update-buddy.log
  #only continue script if upgrades available
  
  LIST="$(apt list --upgradable 2>/dev/null | cut -d/ -f 1 | tail -n +2 | grep -vx "$(dpkg --get-selections | grep "\<hold$" | tr -d ' \t' | sed 's/hold//g' | sed -z 's/\n/\\|/g' | sed -z 's/\\|$/\n/g')")"
  
  if [ -z "$LIST" ];then
    echo "$(date) no packages were found to be upgraded." >> ~/update-buddy.log
    update=0
  fi
  
  echo "$(date) update=1, listing these packages to be upgraded: $LIST" >> ~/update-buddy.log
  if [ $update == 1 ];then
    screen_width="$(xdpyinfo | grep 'dimensions:' | tr 'x' '\n' | tr ' ' '\n' | sed -n 7p)"
    screen_height="$(xdpyinfo | grep 'dimensions:' | tr 'x' '\n' | tr ' ' '\n' | sed -n 8p)"
    
    yad --form --text='Update Buddy:
APT updates available.' \
      --on-top --skip-taskbar --undecorated --close-on-unfocus \
      --geometry=260+$((screen_width-262))+$((screen_height-150)) \
      --image="${DIRECTORY}/logo.png" \
      --button="Details!${DIRECTORY}/icons/info.png":0 \
      --button="Later!${DIRECTORY}/icons/exit.png":1 \
      2>/dev/null || update=0
  fi
  
  if [ $update == 1 ];then
    echo -e "$LIST" | yad --center --title='Update Buddy' --width=310 --height=300 --no-headers --no-selection \
      --list --separator='\n' --window-icon="${DIRECTORY}/logo.png" \
      --text='These packages can be upgraded:' \
      --column=Package \
      --button='Cancel'!"${DIRECTORY}/icons/exit.png"!:1 \
      --button='Update now'!"${DIRECTORY}/icons/download.png":0 \
      2>/dev/null || update=0
  fi
  
  if [ $update == 1 ];then
    "${DIRECTORY}/terminal-run" 'sudo apt -y full-upgrade --allow-downgrades;echo "Closing in 10 seconds.";sleep 10' 'Upgrading packages'
    echo "$(date) user chose to update packages." >> ~/update-buddy.log
  else
    echo "$(date) user chose to not update packages." >> ~/update-buddy.log
  fi
  
  #echo "Waiting 12 hours"
  sleep 12h
done
```

**Comment by Rak1ta** [comment] 2023-08-17 20:28
@Botspot I'll do it in a while.

**Comment by Rak1ta** [comment] 2023-08-17 20:50
@Botspot I don't have any packages to update right now, but errors can be seen.
```
Чт авг 17 23:49:08 MSK 2023 update buddy started.
APT output was: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Err:1 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
  Temporary failure resolving 'adoptopenjdk.jfrog.io'
Err:2 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu bionic InRelease
  Temporary failure resolving 'ppa.launchpadcontent.net'
Err:3 https://ppa.launchpadcontent.net/ubuntu-mozilla-security/rust-next/ubuntu bionic InRelease
  Temporary failure resolving 'ppa.launchpadcontent.net'
Err:4 https://linux.teamviewer.com/deb stable InRelease
  Temporary failure resolving 'linux.teamviewer.com'
Err:5 https://repo.vivaldi.com/stable/deb stable InRelease
  Temporary failure resolving 'repo.vivaldi.com'
Err:6 http://archive.raspberrypi.org/debian buster InRelease
  Temporary failure resolving 'archive.raspberrypi.org'
Err:7 http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/Raspbian_10  InRelease
  Temporary failure resolving 'download.opensuse.org'
Err:8 https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/deb/raspbian buster InRelease
  Temporary failure resolving 'dl.cloudsmith.io'
Err:9 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
  Temporary failure resolving 'itai-nelken.github.io'
Err:10 https://adoptium.jfrog.io/artifactory/deb buster InRelease
  Temporary failure resolving 'adoptium.jfrog.io'
Err:11 http://download.opensuse.org/repositories/home:/stevenpusser/Debian_10  InRelease
  Temporary failure resolving 'download.opensuse.org'
Err:12 https://download.mono-project.com/repo/debian stable-raspbianbuster InRelease
  Temporary failure resolving 'download.mono-project.com'
Err:13 http://pipplware.pplware.pt/pipplware/dists/buster/main/binary ./ InRelease
  Temporary failure resolving 'pipplware.pplware.pt'
Err:14 http://raspbian.raspberrypi.org/raspbian buster InRelease
  Temporary failure resolving 'raspbian.raspberrypi.org'
Reading package lists...
Building dependency tree...
Reading state information...
10 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease  Temporary failure resolving 'raspbian.raspberrypi.org'
W: Failed to fetch https://adoptium.jfrog.io/artifactory/deb/dists/buster/InRelease  Temporary failure resolving 'adoptium.jfrog.io'
W: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/buster/InRelease  Temporary failure resolving 'adoptopenjdk.jfrog.io'
W: Failed to fetch https://itai-nelken.github.io/weekly-box86-debs/debian/InRelease  Temporary failure resolving 'itai-nelken.github.io'
W: Failed to fetch http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/Raspbian_10/InRelease  Temporary failure resolving 'download.opensuse.org'
W: Failed to fetch http://download.opensuse.org/repositories/home:/stevenpusser/Debian_10/InRelease  Temporary failure resolving 'download.opensuse.org'
W: Failed to fetch https://download.mono-project.com/repo/debian/dists/stable-raspbianbuster/InRelease  Temporary failure resolving 'download.mono-project.com'
W: Failed to fetch https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/deb/raspbian/dists/buster/InRelease  Temporary failure resolving 'dl.cloudsmith.io'
W: Failed to fetch https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'ppa.launchpadcontent.net'
W: Failed to fetch http://pipplware.pplware.pt/pipplware/dists/buster/main/binary/./InRelease  Temporary failure resolving 'pipplware.pplware.pt'
W: Failed to fetch http://archive.raspberrypi.org/debian/dists/buster/InRelease  Temporary failure resolving 'archive.raspberrypi.org'
W: Failed to fetch https://linux.teamviewer.com/deb/dists/stable/InRelease  Temporary failure resolving 'linux.teamviewer.com'
W: Failed to fetch https://ppa.launchpadcontent.net/ubuntu-mozilla-security/rust-next/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'ppa.launchpadcontent.net'
W: Failed to fetch https://repo.vivaldi.com/stable/deb/dists/stable/InRelease  Temporary failure resolving 'repo.vivaldi.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Thu 17 Aug 2023 11:49:17 PM MSK update=1, listing these packages to be upgraded: linux-libc-dev
Thu 17 Aug 2023 11:49:20 PM MSK user chose to not update packages.
```

**Comment by Rak1ta** [comment] 2023-08-17 20:58
If `sudo ~/update-buddy/onstartup.sh`
```
Чт авг 17 23:57:28 MSK 2023 update buddy started.
APT output was: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/Raspbian_10  InRelease [1,542 B]
Get:2 http://download.opensuse.org/repositories/home:/stevenpusser/Debian_10  InRelease [1,547 B]
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
Hit:4 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:5 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:6 https://download.mono-project.com/repo/debian stable-raspbianbuster InRelease
Hit:7 https://linux.teamviewer.com/deb stable InRelease
Hit:8 http://pipplware.pplware.pt/pipplware/dists/buster/main/binary ./ InRelease
Ign:9 https://repo.vivaldi.com/stable/deb stable InRelease
Hit:10 https://repo.vivaldi.com/stable/deb stable Release
Hit:11 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu bionic InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntu-mozilla-security/rust-next/ubuntu bionic InRelease
Hit:13 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
Get:14 https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/deb/raspbian buster InRelease [5,104 B]
Hit:15 https://adoptium.jfrog.io/artifactory/deb buster InRelease
Fetched 8,193 B in 4s (2,060 B/s)
Reading package lists...
Building dependency tree...
Reading state information...
10 packages can be upgraded. Run 'apt list --upgradable' to see them.
Thu 17 Aug 2023 11:57:37 PM MSK update=1, listing these packages to be upgraded: linux-libc-dev
```
but `linux-libc-dev` hidden for update

**Comment by Botspot** [comment] 2023-08-17 21:22
OK, I think the problem is that on your setup, Update Buddy runs before there is a stable Internet connection.

**Closed as completed** 2023-08-17 21:25 UTC

**Comment by Rak1ta** [comment] 2023-08-17 21:27
> stable Internet connection

This does not affect operation. Update doesn't happen [without](https://github.com/Botspot/update-buddy/issues/3#issuecomment-1682971442) `sudo`. And the raspberry is connected via a patch cord to the router.

**Comment by Botspot** [comment] 2023-08-17 21:31
Update buddy already uses `sudo` to run `apt update`. If it really was not doing that, then the output would look more like this:
```
$ apt update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
```
The errors seen from when Update Buddy ran on boot clearly indicate an Internet problem. This happens on my system too - my Ethernet connection does not stabilize until a few seconds after the desktop environment appears.

**Comment by Rak1ta** [comment] 2023-08-17 21:35
@Botspot My RPI is still enabled.
```
Пт авг 18 00:32:14 MSK 2023 update buddy started.
APT output was: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/Raspbian_10  InRelease [1,542 B]
Get:2 http://download.opensuse.org/repositories/home:/stevenpusser/Debian_10  InRelease [1,547 B]
Hit:3 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
```
```
Чт авг 17 23:49:08 MSK 2023 update buddy started.
APT output was: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Err:1 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
  Temporary failure resolving 'adoptopenjdk.jfrog.io'
Err:2 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu bionic InRelease
  Temporary failure resolving 'ppa.launchpadcontent.net'
Err:3 https://ppa.launchpadcontent.net/ubuntu-mozilla-security/rust-next/ubuntu bionic InRelease
  Temporary failure resolving 'ppa.launchpadcontent.net'
```

**Comment by Botspot** [comment] 2023-08-17 21:37
That is still the old version. You need to manually update to the new version of onstartup.sh, or allow pi-apps to reinstall Update Buddy for you.

**Comment by Rak1ta** [comment] 2023-08-17 21:41
@Botspot Is it possible to make an autostart with a delayed start in 1 minute (for example)?
It seems to me that 5 minutes is a lot. at least two.

**Comment by Botspot** [comment] 2023-08-17 22:03
Well I didn't want `apt update` to be running every minute forever in some cases. But You did remind me of a particular retry algorithm which is exponential - wait 1 minute, then wait 2 minutes, then wait 4 minutes... I will do that.

**Comment by Botspot** [comment] 2023-08-17 22:07
Done. I will not be bumping the pi-apps script again as everyone else has likely not yet updated.

**Comment by Botspot** [comment] 2023-09-21 04:19
Just wanted to make sure this seems to be working for you, @Rak1ta.

**Comment by Rak1ta** [comment] 2023-09-21 06:21
Works great, @Botspot.
